function New-LogReport {
    param
    (
        $Logs,
        $Errors,
        $Warnings,
        $Skipped
    )

    $_template = [System.Text.StringBuilder]::new(
        "!!! Log report generated by ABPE Log Tool !!!

All Logs: $($Logs.Count ?? 0); Errors: $($Errors.Count ?? 0); Warnings: $($Warnings.Count ?? 0); Skipped: $($Skipped.Count ?? 0);

Skipped runnings:
----------------
Date`t`tTime`t`tSupplier`t`tProduct Order`t`tMessage

");

    $Skipped | ForEach-Object { 
        [void]$_template.Append("$($_.Date)`t$($_.Time)`t$($_.Supplier)`t`t$($_.'Product Order')`t$($_."Message")`n") 
    }

    [void]$_template.Append("`nErrors:`n")
    [void]$_template.Append("----------------`n")
    
    $Errors | ForEach-Object { 
        [void]$_template.Append("$($_.Date)`t$($_.Time)`t$($_.Supplier)`t`t$($_.'Product Order')`t$($_."Message")`n") 
    }

    [void]$_template.Append("`nWarnings:`n")
    [void]$_template.Append("----------------`n")
    
    $Warnings | ForEach-Object { 
        [void]$_template.Append("$($_.Date)`t$($_.Time)`t$($_.Supplier)`t`t$($_.'Product Order')`t$($_."Message")`n") 
    }

    return $_template.ToString()

}


function ConvertTo-LogsObject {
    param (
        $Logs
    )

    if ($null -ne $Logs) {
        $_logs = $Logs | Select-Object @{n = "Date"; e = { $_."Date" } },
        @{n = "Time"; e = { $_."Time" } },
        @{n = "Supplier"; e = { $_.Message | Find-ProductOrderOrSupplierNumber -Supplier } },
        @{n = "Product Order"; e = { $_.Message | Find-ProductOrderOrSupplierNumber -Order } },
        @{n = "Message"; e = { $_.Message } },
        @{n = "Log Level"; e = { $_."Properties_LogLevel" } },
        @{n = "Severity Level"; e = { $_."SeverityLevel" } },
        @{n = "Invocation Id"; e = { $_."Properties_InvocationId" } }

        return $_logs
    }

    Write-Warning "The Logs argument is null!"
    return $null
}

function Sync-LocallyLogReport {
    param (
        
        $WorkspaceId,
        $SyncedEntities
    )

    $syncedEntities = $SyncedEntities;

    $reprocessing = @{
        suppliers     = [System.Collections.Generic.HashSet[object]]::new();
        productOrders = [System.Collections.Generic.HashSet[object]]::new()
    }

    foreach ($syncEntity in $syncedEntities) {
    
        $InvocationId = $syncEntity.Properties_InvocationId
        $OperationId = $syncEntity.OperationId
        $AppRoleName = $syncEntity.AppRoleName

        $logs = Get-AllLogsFromSyncedEntities -WorkspaceId $WorkspaceId -OperationId $OperationId -InvocationId $InvocationId

        if ($null -ne $logs) {

            $basePath = Join-Path -Path "./logs" -ChildPath $AppRoleName 
            $mainDownloadPath = Join-Path -Path $basePath -ChildPath $syncEntity.Date 
            if ((Test-Path -Path $mainDownloadPath) -eq $false) {
                New-Item -ItemType Directory -Name $mainDownloadPath | Out-Null
            }
    
            $subDownloadPath = Join-Path -Path $mainDownloadPath -ChildPath $syncEntity.Time.Replace(":", "_")
            $csvDownloadPath = Join-Path -Path $subDownloadPath -ChildPath "/csv"
            if ((Test-Path -Path $csvDownloadPath) -eq $false) {
                New-Item -ItemType Directory -Name $csvDownloadPath | Out-Null
            }

            if ($null -eq $logs ) { Write-Warning "No logs found for datetime: $($syncEntity.Date) - $($syncEntity.Time)!" }
            $logs = ConvertTo-LogsObject -Logs $logs
            $pathToSaveAllLogs = Join-Path -Path $csvDownloadPath -ChildPath "all.csv"
            Save-CsvLog -PathToSave $pathToSaveAllLogs -Logs $logs | Out-Null

            ## save warnings
            $_warning_logs = $logs | Where-Object { $_."Severity Level" -eq 2 }
            if ($null -eq $_warning_logs ) { Write-Warning "No warnings logs found for datetime: $($syncEntity.Date) - $($syncEntity.Time)!" }
            $pathToSaveWarnings = Join-Path -Path $csvDownloadPath -ChildPath "warnings.csv"
            Save-CsvLog -PathToSave $pathToSaveWarnings -Logs $_warning_logs | Out-Null

            # save errors
            $_error_logs = $logs | Where-Object { ($_."Severity Level" -eq 3) -and !$_.Message.ToLower().Contains("skip") }
            if ($null -eq $_error_logs ) { Write-Warning "No error logs found for datetime: $($syncEntity.Date) - $($syncEntity.Time)!" }
            $pathToSaveErrors = Join-Path -Path $csvDownloadPath -ChildPath "errors.csv"
            Save-CsvLog -PathToSave $pathToSaveErrors -Logs $_error_logs | Out-Null

            #Skipped logs:
            $_skippedLogs = Find-SkippedProductOrder -Logs $logs;
            if ($null -eq $_skippedLogs ) { Write-Warning "No error logs found for datetime: $($syncEntity.Date) - $($syncEntity.Time)!" }
            $pathToSaveSkippedErrors = Join-Path -Path $csvDownloadPath -ChildPath "skipped.csv"
            Save-CsvLog -PathToSave $pathToSaveSkippedErrors -Logs $_skippedLogs | Out-Null

            ## Save excel files 
            $excelDownloadPath = Join-Path -Path $subDownloadPath -ChildPath "/excel"
            if ((Test-Path -Path $excelDownloadPath) -eq $false) {
                New-Item -ItemType Directory -Name $excelDownloadPath | Out-Null
            }

            $pathToSaveAllLogsExcel = Join-Path -Path $excelDownloadPath -ChildPath "all.xlsx"
            Save-ExcelFile -PathToSave $pathToSaveAllLogsExcel -WorksheetName "logs" -Logs $logs | Out-Null

            $pathToSaveWarnLogsExcel = Join-Path -Path $excelDownloadPath -ChildPath "warnings.xlsx"
            Save-ExcelFile -PathToSave $pathToSaveWarnLogsExcel -WorksheetName "logs" -Logs $_warning_logs | Out-Null
        
            $pathToSaveErrLogsExcel = Join-Path -Path $excelDownloadPath -ChildPath "error.xlsx"
            Save-ExcelFile -PathToSave $pathToSaveErrLogsExcel -WorksheetName "logs" -Logs $_error_logs | Out-Null

            $pathToSaveSkippedLogsExcel = Join-Path -Path $excelDownloadPath -ChildPath "skipped.xlsx"
            Save-ExcelFile -PathToSave $pathToSaveSkippedLogsExcel -WorksheetName "logs" -Logs $_skippedLogs | Out-Null
        
            #Log reports
            $report = New-LogReport -Logs $logs -Errors $_error_logs -Warnings $_warning_logs -Skipped $_skippedLogs;
            $pathToSaveLogReport = Join-Path -Path $subDownloadPath -ChildPath "report.txt"
            Save-LogReport -PathToSave $pathToSaveLogReport -TextLogReport $report | Out-Null

            #add suppliers from error logs to reprocess
            $suppliers = $_error_logs | Where-Object { $null -ne $_.'Supplier' } | Select-Object -ExpandProperty 'Supplier' -Unique
            if ($null -ne $suppliers) {
                if ($suppliers -is [System.String]) {
                    $reprocessing.suppliers.Add($suppliers) | Out-Null
                }
                else {
                    $reprocessing.suppliers.UnionWith($suppliers)
                }
            }

            #add product orders from error logs to reprocess
            $productOrders = $_error_logs | Where-Object { ($null -ne $_.'Product Order') -and ($_.'Message'.ToLower().Contains("spend") -ne $true) } | Select-Object -ExpandProperty 'Product Order' -Unique
            if ($null -ne $productOrders) {
                if ($productOrders -is [System.String]) {
                    $reprocessing.productOrders.Add($productOrders) | Out-Null
                }
                else {
                    $reprocessing.productOrders.UnionWith($productOrders)
                }
            }
        
        }

        if ($null -eq $logs) {
            Write-Warning "No logs from: $($syncEntity.AppRoleName) at $($syncEntity.Date) to save locally!"
        }
    }

    return $reprocessing
}